import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Building2,FolderOpen,Plus,Search,ArrowRight,RefreshCw} from 'lucide-react';
import {listProjects,createProject,setProjectCancelled,type ProjectRow} from './lib/project-api';
import {workspaceCopy} from './workspace-copy';
import {useAuth} from './auth';
import type {Language} from './seller-copy';
import {QuebecCityOptions,QUEBEC_CITY_LIST_ID} from './quebec-cities';

export function Projects({lang}:{lang:Language}){
  const c=workspaceCopy[lang]; const {user,staffRole}=useAuth();
  const [rows,setRows]=useState<ProjectRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(false);
  const t=(fr:string,en:string,zh:string)=>({fr,en,zh})[lang];
  const [cancelling,setCancelling]=useState<ProjectRow|null>(null),[changing,setChanging]=useState(false),[changeError,setChangeError]=useState(false);
  async function changeCancellation(project:ProjectRow,cancelled:boolean){if(changing)return;setChanging(true);setChangeError(false);try{const updated=await setProjectCancelled(project,cancelled);setRows(current=>current.map(r=>r.id===updated.id?updated:r));setCancelling(null);}catch{setChangeError(true);}finally{setChanging(false);}}
  const [query,setQuery]=useState(''),[status,setStatus]=useState(''),[sort,setSort]=useState('new'),[page,setPage]=useState(0);
  const [creating,setCreating]=useState(false),[saving,setSaving]=useState(false),[createError,setCreateError]=useState(false),[reload,setReload]=useState(0);
  const requestId=useRef('');const submitting=useRef(false);
  useEffect(()=>{let active=true;setLoading(true);setError(false);setRows([]);listProjects().then(data=>{if(active)setRows(data);}).catch(()=>{if(active)setError(true);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[user?.id,reload]);
  const filtered=rows.filter(row=>(status==='cancelled'?!!row.cancelled_at:!row.cancelled_at&&(!status||row.status===status))&&`${row.details.address||''} ${row.details.city||''}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).sort((a,b)=>(sort==='new'?-1:1)*a.updated_at.localeCompare(b.updated_at));
  const pages=Math.max(1,Math.ceil(filtered.length/10));const current=Math.min(page,pages-1);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(submitting.current)return;submitting.current=true;setSaving(true);setCreateError(false);const data=new FormData(event.currentTarget);
    try{const project=await createProject(requestId.current,String(data.get('address')),String(data.get('city')),data.get('plan')==='with'?'with':'without');location.hash=`projects/${project.id}/edit`;}
    catch{setCreateError(true);}finally{submitting.current=false;setSaving(false);}}
  return <div className="workspace-shell"><aside className="workspace-nav">{staffRole&&<a href="#admin">{t("Administration","Administration","管理后台")}</a>}<a className="selected" href="#projects"><FolderOpen/>{c.title}</a><a href="#proprietes"><Building2/>{lang==='fr'?'Propriétés':lang==='en'?'Properties':'公开房源'}</a></aside><section className="projects-main">
    <div className="projects-heading"><div><p className="workspace-breadcrumb">Propriété En Vente / {c.title}</p><h1>{c.title}</h1><p>{c.subtitle}</p></div><button disabled={creating} onClick={()=>{requestId.current=crypto.randomUUID();setCreating(true);setCreateError(false);}}><Plus/>{c.create}</button></div>
    {changeError&&<p role="alert">{t("Modification impossible. Actualisez puis réessayez.","Unable to update. Refresh and retry.","修改未成功，请刷新后重试。")}</p>}
    {cancelling&&<section className="new-project-panel" role="dialog" aria-modal="true" aria-label={t("Annuler le projet","Cancel project","取消项目")}><h2>{t("Annuler le projet","Cancel project","取消项目")} · {cancelling.details.address}</h2><p>{t("Le dossier sera déplacé dans les projets annulés. Ses documents et rendez-vous seront conservés et vous pourrez le rétablir. Les annonces publiques se gèrent séparément dans l’administration.","The project will move to Cancelled. Documents and appointments are preserved, and you can restore it. Public listings are managed separately in administration.","项目会移至“已取消”，资料和看房记录保留，可随时恢复。公开房源需在管理后台单独下架。")}</p><div className="project-form-actions"><button disabled={changing} onClick={()=>void changeCancellation(cancelling,true)}>{changing?c.loading:t("Confirmer l’annulation","Confirm cancellation","确认取消项目")}</button><button className="secondary" disabled={changing} onClick={()=>setCancelling(null)}>{t("Garder le projet","Keep project","保留项目")}</button></div></section>}
    <div className="project-counts">{[[c.total,rows.length],[c.drafts,rows.filter(r=>!r.cancelled_at&&r.status==='draft').length],[c.submitted,rows.filter(r=>!r.cancelled_at&&r.status==='submitted').length],[c.approved,rows.filter(r=>!r.cancelled_at&&r.status==='approved').length]].map(([label,value])=><div key={label}><span>{label}</span><strong>{loading||error?'—':value}</strong></div>)}</div>
    {creating&&<form onSubmit={create} className="new-project-panel"><h2>{c.newTitle}</h2><div className="new-project-fields"><label>{c.address}<input autoFocus name="address" required minLength={3} maxLength={200} disabled={saving}/></label><QuebecCityOptions><label>{c.city}<input name="city" list={QUEBEC_CITY_LIST_ID} autoComplete="address-level2" required minLength={2} maxLength={100} disabled={saving}/></label></QuebecCityOptions><label>{c.plan}<select name="plan" disabled={saving}><option value="without">{c.self}</option><option value="with">{c.broker}</option></select></label></div>{createError&&<p role="alert">{c.createError}</p>}<div className="project-form-actions"><button className="secondary" type="button" disabled={saving} onClick={()=>setCreating(false)}>{c.cancel}</button><button disabled={saving}>{saving?c.loading:c.save}</button></div></form>}
    <div className="project-table-panel"><div className="project-table-tools"><label className="project-search"><Search/><input aria-label={c.search} placeholder={c.search} value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><select aria-label={c.status} value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">{t("Projets actifs","Active projects","进行中的项目")}</option><option value="cancelled">{t("Annulés","Cancelled","已取消")}</option>{Object.entries(c.statuses).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select><select aria-label={c.sort} value={sort} onChange={e=>{setSort(e.target.value);setPage(0);}}><option value="new">{c.newest}</option><option value="old">{c.oldest}</option></select><button className="secondary" aria-label={c.retry} onClick={()=>setReload(n=>n+1)} disabled={loading}><RefreshCw/></button></div>
    {loading?<p className="project-empty" role="status">{c.loading}</p>:error?<div className="project-empty" role="alert"><p>{c.error}</p><button onClick={()=>setReload(n=>n+1)}>{c.retry}</button></div>:!filtered.length?<div className="project-empty"><FolderOpen/><h2>{rows.length?c.noResults:c.empty}</h2>{!rows.length&&<p>{c.emptyText}</p>}</div>:<><div className="project-table-scroll"><table><thead><tr>{[c.address,c.city,c.plan,c.status,c.updated,c.actions].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{filtered.slice(current*10,current*10+10).map(row=><tr key={row.id}><td data-label={c.address}><a href={`#projects/${row.id}/overview`}>{row.details.address||c.newTitle}</a><small>{row.id.slice(0,8).toUpperCase()}</small></td><td data-label={c.city}>{row.details.city||'—'}</td><td data-label={c.plan}>{row.plan==='with'?c.broker:c.self}</td><td data-label={c.status}><span className={`project-badge ${row.status}`}>{row.cancelled_at?t("Annulé","Cancelled","已取消"):c.statuses[row.status]}</span></td><td data-label={c.updated}>{new Intl.DateTimeFormat(lang==='zh'?'zh-CN':`${lang}-CA`,{dateStyle:'medium'}).format(new Date(row.updated_at))}</td><td data-label={c.actions} className="project-actions-cell"><div className="project-row-actions"><a className="project-open" href={`#projects/${row.id}/overview`}>{c.open}<ArrowRight/></a><button type="button" className="project-cancel-action" disabled={changing} onClick={()=>row.cancelled_at?void changeCancellation(row,false):setCancelling(row)}>{row.cancelled_at?t("Rétablir","Restore","恢复项目"):t("Annuler le projet","Cancel project","取消项目")}</button></div></td></tr>)}</tbody></table></div><div className="project-pagination"><span>{filtered.length} {c.total} · {current+1} / {pages}</span><button className="secondary" disabled={current===0} onClick={()=>setPage(current-1)}>{c.previous}</button><button className="secondary" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>{c.next}</button></div></>}
    </div></section></div>;
}
