export const recoveryCopy = {
  en: {
    checkEmail: "Check your email",
    sent: "If this address belongs to an account, a password reset link will be sent to it.",
    hint: "Check your inbox and spam folder. Use the most recent link to choose a new password.",
    resend: "Resend reset link",
    change: "Use another email address",
    failed: "We couldn’t send the reset request. Check your connection and try again.",
    rateLimit: "Please wait a minute before requesting another link.",
    success: "Your password has been updated",
    continue: "Continue to my workspace",
  },
  fr: {
    checkEmail: "Consultez votre boîte courriel",
    sent: "Si cette adresse correspond à un compte, un lien de réinitialisation lui sera envoyé.",
    hint: "Vérifiez votre boîte de réception et les courriers indésirables. Utilisez le lien le plus récent pour choisir un nouveau mot de passe.",
    resend: "Renvoyer le lien",
    change: "Utiliser une autre adresse courriel",
    failed: "Impossible d’envoyer la demande. Vérifiez votre connexion et réessayez.",
    rateLimit: "Veuillez patienter une minute avant de demander un nouveau lien.",
    success: "Votre mot de passe a été modifié",
    continue: "Accéder à mon espace",
  },
  zh: {
    checkEmail: "请查看邮箱",
    sent: "如果此邮箱对应已注册账号，系统会向它发送密码重置链接。",
    hint: "请检查收件箱和垃圾邮件，使用最新邮件中的链接设置新密码。",
    resend: "重新发送重置链接",
    change: "使用其他邮箱",
    failed: "重置请求未能发送，请检查网络后重试。",
    rateLimit: "请等待一分钟后再申请重置链接。",
    success: "密码已修改成功",
    continue: "进入我的工作台",
  },
};
